version: '3.8'

services:
  fastapi-app:
    container_name: fastapi-app
    build: ./
    ports:
      - 8000:80
#    volumes:
#      - ./app:/app/app
    depends_on:
      - db
    env_file: .env
    restart: always
    networks:
      - ecommerce-network
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"

  db:
    container_name: db
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - ecommerce-network

volumes:
  mysql-db:

networks:
  ecommerce-network:
    driver: bridge